name: Deploy Python Code

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Change to your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have a requirements.txt file

    - name: Set up Firebase credentials
      run: echo "${{ secrets.FIREBASE_CREDENTIALS }}" > firebase-credentials.json

    - name: Run the Python script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: firebase-credentials.json  # Set environment variable
        exit-scanner: ${{ secrets.FIREBASE_CREDENTIALS }}  # Added environment variable
      run: python app.py  # Change this to your actual script name

    - name: Clean up
      run: rm firebase-credentials.json
